<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A disclaimer will be added to the public library.' => 'Этот виджет будет добавлен в публичной библиотеке.',
  'A public library will be added to the top menu. It contains all public library categories from all spaces.' => 'Публичная библиотека будет добавлена в верхнее меню. Она содержит все публичные категории из всех пространств.',
  'Disclaimer content' => 'Текст',
  'Disclaimer title' => 'Заголовок',
  'Disclaimer widget' => 'Виджет с отказом от ответственности или лицензией',
  'Enable global public library.' => 'Разрешить глобальную публичную библиотеку.',
  'Extend link validation by a connection test.' => 'Проверять внешние ссылки на возможность подключения.',
  'Global public library' => 'Глобальная публичная библиотека',
  'Library Module Configuration' => 'Настройка модуля "Библиотека"',
  'Library configuration' => 'Настройка библиотеки',
  'Only publishers/admins can add items to any category.' => 'Только Редакторы/Администраторы могут добавлять элементы в любую категорию.',
  'Show disclaimer widget in global public library.' => 'Показывать виджет с отказом от ответственности.',
  'Show selected library categories in a sidebar widget.' => 'Показывать выбранные категории в боковом меню.',
  'You can configure extended functionality of this module for a space or user.' => 'Вы можете настроить расширенные функциональные возможности этого модуля для пространства или пользователя..',
);
