<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Confirm</strong> category deleting' => '<strong>Подтверждение</strong> удаления категории',
  '<strong>Confirm</strong> item deleting' => '<strong>Подтверждение</strong> удаления материала',
  '<strong>Create</strong> new category' => '<strong>Создание</strong> новой категории',
  '<strong>Create</strong> new document' => '<strong>Создание</strong> нового документа',
  '<strong>Create</strong> new link' => '<strong>Создание</strong> новой ссылки',
  '<strong>Edit</strong> category' => '<strong>Редактирование</strong> категории',
  '<strong>Edit</strong> document' => '<strong>Редактирование</strong> документа',
  '<strong>Edit</strong> link' => '<strong>Редактирование</strong> ссылки',
  '<strong>Public</strong> libraries' => '<strong>Публичная</strong> библиотека',
  'A disclaimer will be added to the public library.' => 'Этот виджет будет добавлен в публичной библиотеке.',
  'A public library will be added to the top menu. It contains all public library categories from all spaces.' => 'Публичная библиотека будет добавлена в верхнее меню. Она содержит все категории публичных библиотек из всех пространств.',
  'Add category' => 'Добавить категорию',
  'Add document' => 'Добавить документ',
  'Add link' => 'Добавить ссылку',
  'Added a new document %document% to category "%category%".' => 'Добавлен новый документ %document% в категорию "%category%".',
  'Added a new link %link% to category "%category%".' => 'Добавлена новая ссылка %link% в категорию "%category%".',
  'All users can access items in public categories. Only publishers can add items.' => 'Все пользователи имеют доступ к публичным категориям. Только Редакторы/Администраторы могут добавлять элементы.',
  'Back to library' => 'Назад в библиотеку',
  'Cancel' => 'Отмена',
  'Delete' => 'Удалить',
  'Delete category' => 'Удалить категорию',
  'Delete item' => 'Удалить материал',
  'Description' => 'Описание',
  'Disclaimer' => 'Отказ от ответственности',
  'Disclaimer content' => 'Текст',
  'Disclaimer title' => 'Заголовок',
  'Disclaimer widget' => 'Виджет с отказом от ответственности',
  'Do you really want to delete this category? All connected items will be lost!' => 'Вы действительно хотите удалить эту категорию? Все содержимое будет потеряно!',
  'Do you really want to delete this item?' => 'Вы действительно хотите удалить этот материал?',
  'Document' => 'Документ',
  'Document date' => 'Дата документа',
  'Edit category' => 'Редактировать категорию',
  'Edit item' => 'Редактировать материал',
  'Enable global public library.' => 'Разрешить глобальную публичную библиотеку.',
  'Extend link validation by a connection test.' => 'Проверять внешние ссылки на возможность подключения.',
  'File' => 'Файл',
  'Global public library' => 'Глобальная публичная библиотека',
  'ID' => 'ID',
  'If you upload multiple files, only the last file will be saved.' => 'Если вы загружаете сразу несколько файлов, только последний файл будет сохранен.',
  'Library' => 'Библиотека',
  'Library Module Configuration' => 'Конфигурация модуля "Библиотека"',
  'Library configuration' => 'Конфигурация библиотеки',
  'LibraryCategory' => 'Категория',
  'Link' => 'Ссылка',
  'No public categories have been added to any space library yet.' => 'Публичных категорий еще не было добавлено ни в одном пространстве.',
  'Only publishers/admins can add items to any category.' => 'Только Редакторы/Администраторы могут добавлять элементы в любую категорию.',
  'Quick' => 'Быстро',
  'Save' => 'Сохранить',
  'Set a custom disclaimer text or disable the disclaimer widget in the library module configuration.' => 'Установить свой текст виджета с отказом от ответственности или отключить его в конфигурации модуля.',
  'Show disclaimer widget in global public library.' => 'Показывать виджет с отказом от ответственности в публичной библиотеке.',
  'Show selected library categories in a sidebar widget.' => 'Показывать эту библиотеку в боковом меню.',
  'Show this category in sidebar widget.' => 'Показывать эту категорию в боковом меню.',
  'Sort order' => 'Сортировка пунктов',
  'The item order was successfully changed.' => 'Порядок сортировки успешно изменен.',
  'There have been no items or categories added to this space yet.' => 'Нет ни одного публичного материала, в этом пространстве.',
  'There have been no public categories added to this space yet.' => 'Нет ни одной публичной категории, в этом пространстве.',
  'This is a public category.' => 'Это публичная категория.',
  'Title' => 'Заголовок',
  'URL' => 'URL',
  'You can configure extended functionality of this module for a space or user.' => 'Вы можете настроить расширенные функциональные возможности этого модуля для пространства или пользователя.',
  'You must upload a file.' => 'Вы должны загрузить файл.',
  'library' => 'Библиотека',
);
