<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Requested category could not be found.' => 'Запрашиваемая категория не найдена.',
  'Requested item could not be found.' => 'Запрашиваемый элемент не найден.',
  'The category you want to create your document in could not be found!' => 'Категория, в которой вы хотите создать документ, не найдена!',
  'The category you want to create your link in could not be found!' => 'Категория, в которой вы хотите создать ссылку, не найдена!',
  'The item you want to edit could not be found!' => 'Элемент, который вы хотите редактировать, не найден!',
  'You miss the rights to add documents to public categories!' => 'У вас нет прав добавлять документы в публичные категории!',
  'You miss the rights to add documents!' => 'У вас нет прав добавлять документы!',
  'You miss the rights to add links to public categories!' => 'У вас нет прав добавлять ссылки в публичные категории!',
  'You miss the rights to add links!' => 'У вас нет прав добавлять ссылки!',
  'You miss the rights to add/edit items!' => 'У вас нет прав добавлять/редактировать элементы!',
  'You miss the rights to delete this category!' => 'У вас нет прав на удаление этой категории!',
  'You miss the rights to delete this item!' => 'У вас нет прав на удаление этого элемента!',
  'You miss the rights to edit this category!' => 'У вас нет прав на редактирование этой категории!',
  'You miss the rights to edit this document!' => 'У вас нет прав на редактирование этого документа!',
  'You miss the rights to reorder categories!' => 'У вас нет прав на изменение порядка категорий!',
  'You miss the rights to reorder items!' => 'У вас нет прав на изменение порядка элементов!',
);
