<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A disclaimer will be added to the public library.' => 'In der öffentlichen Bibliothek wird ein Nutzungshinweis angezeigt.',
  'A public library will be added to the top menu. It contains all public library categories from all spaces.' => 'Im Hauptmenü wird eine öffentliche Bibliothek hinzugefügt. Sie enthält alle öffentlichen Kategorien aller Spaces.',
  'Disclaimer content' => 'Hinweistext',
  'Disclaimer title' => 'Hinweistitel',
  'Disclaimer widget' => 'Hinweis-Widget',
  'Enable global public library.' => 'Globale öffentliche Bibliothek aktivieren.',
  'Extend link validation by a connection test.' => 'Links zusätzlich durch einen Verbindungstest verifizieren.',
  'Global public library' => 'Globale öffentliche Bibliothek',
  'Library Module Configuration' => 'Konfiguration des Bibliotheksmoduls',
  'Library configuration' => 'Konfiguration der Bibliothek',
  'Only publishers/admins can add items to any category.' => 'Nur Veröffentlicher/Admins können Einträge in Kategorien hinzufügen.',
  'Show disclaimer widget in global public library.' => 'Hinweis-Widget in der globalen öffentlichen Bibliothek anzeigen.',
  'Show selected library categories in a sidebar widget.' => 'Ausgewählte Bibliothekskategorien in einem Seitenleisten-Widget anzeigen.',
  'You can configure extended functionality of this module for a space or user.' => 'Sie können erweiterte Funktionen dieses Moduls für einen Space oder Benutzer konfigurieren.',
);
