<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'No public categories have been added to any space library yet.' => 'Bisher gibt es leider noch keine öffentlichen Kategorien in Bibliotheken.',
  '<strong>Confirm</strong> category deleting' => '<strong>Bestätigen</strong> Sie das Löschen der Kategorie',
  '<strong>Confirm</strong> item deleting' => '<strong>Bestätigen</strong> Sie das Löschen des Eintrags',
  '<strong>Create</strong> new category' => '<strong>Kategorie</strong> hinzufügen',
  '<strong>Create</strong> new document' => '<strong>Dokument</strong> hinzufügen',
  '<strong>Create</strong> new link' => '<strong>Link</strong> hinzufügen',
  '<strong>Edit</strong> category' => '<strong>Kategorie</strong> bearbeiten',
  '<strong>Edit</strong> document' => '<strong>Dokument</strong> bearbeiten',
  '<strong>Edit</strong> link' => '<strong>Link</strong> bearbeiten',
  '<strong>Public</strong> libraries' => '<strong>Öffentliche</strong> Bibliotheken',
  'A disclaimer will be added to the public library.' => 'In der öffentlichen Bibliothek wird ein Nutzungshinweis angezeigt.',
  'A public library will be added to the top menu. It contains all public library categories from all spaces.' => 'Im Hauptmenü wird eine öffentliche Bibliothek hinzugefügt. Sie enthält alle öffentlichen Kategorien aller Spaces.',
  'Add category' => 'Kategorie hinzufügen',
  'Add document' => 'Dokument hinzufügen',
  'Add link' => 'Link hinzufügen',
  'Added a new document %document% to category "%category%".' => 'Ein neues Dokument %document% wurde der Kategorie "%category%" hinzugefügt.',
  'Added a new link %link% to category "%category%".' => 'Ein neuer Link %link% wurde der Kategorie "%category%" hinzugefügt.',
  'All users can access items in public categories. Only publishers can add items.' => 'Jeder hat Zugriff auf Inhalte in öffentlichen Kategorien. Nur Veröffentlicher können Einträge hinzufügen.',
  'Back to library' => 'Zurück zur Bibliothek',
  'Cancel' => 'Abbrechen',
  'Delete' => 'Löschen',
  'Delete category' => 'Kategorie löschen',
  'Delete item' => 'Eintrag löschen',
  'Description' => 'Beschreibung',
  'Disclaimer' => 'Nutzungshinweis',
  'Disclaimer content' => 'Hinweistext',
  'Disclaimer title' => 'Hinweistitel',
  'Disclaimer widget' => 'Hinweis-Widget',
  'Do you really want to delete this category? All connected items will be lost!' => 'Möchten Sie diese Kategorie wirklich löschen? Alle Einträge werden unwiderruflich gelöscht!',
  'Do you really want to delete this item?' => 'Möchten Sie diesen Eintrag wirklich löschen?',
  'Document' => 'Dokument',
  'Document date' => 'Datum',
  'Edit category' => 'Kategorie bearbeiten',
  'Edit item' => 'Eintrag bearbeiten',
  'Enable global public library.' => 'Globale öffentliche Bibliothek aktivieren.',
  'Extend link validation by a connection test.' => 'Links zusätzlich durch einen Verbindungstest verifizieren.',
  'File' => 'Datei',
  'Global public library' => 'Globale öffentliche Bibliothek',
  'ID' => 'ID',
  'If you upload multiple files, only the last file will be saved.' => 'Wenn Sie mehrere Dateien hochladen, wird nur die letzte Datei gespeichert.',
  'Library' => 'Bibliothek',
  'Library Module Configuration' => 'Konfiguration des Bibliotheksmoduls',
  'Library configuration' => 'Konfiguration der Bibliothek',
  'LibraryCategory' => 'BibliotheksKategorie',
  'Link' => 'Link',
  'Only publishers/admins can add items to any category.' => 'Nur Veröffentlicher/Admins können Einträge in Kategorien hinzufügen.',
  'Quick' => 'Schnell',
  'Save' => 'Speichern',
  'Set a custom disclaimer text or disable the disclaimer widget in the library module configuration.' => 'Konfigurieren Sie einen eigenen Hinweistext oder deaktivieren Sie das Hinweis-Widget in der Konfiguration des Bibliotheksmoduls.',
  'Show disclaimer widget in global public library.' => 'Hinweis-Widget in der globalen öffentlichen Bibliothek anzeigen.',
  'Show selected library categories in a sidebar widget.' => 'Ausgewählte Bibliothekskategorien in einem Seitenleisten-Widget anzeigen.',
  'Show this category in sidebar widget.' => 'Diese Kategorie im Seitenleisten-Widget anzeigen.',
  'Sort order' => 'Sortierreihenfolge',
  'The item order was successfully changed.' => 'Die Reihenfolge der Einträge wurde erfolgreich geändert.',
  'There have been no items or categories added to this space yet.' => 'Zu diesem Space wurden noch keine Einträge oder Kategorien hinzugefügt.',
  'There have been no public categories added to this space yet.' => 'Zu diesem Space wurden noch keine öffentlichen Kategorien hinzugefügt.',
  'This is a public category.' => 'Dies ist eine öffentliche Kategorie.',
  'Title' => 'Titel',
  'URL' => 'URL',
  'You can configure extended functionality of this module for a space or user.' => 'Sie können erweiterte Funktionen dieses Moduls für einen Space oder Benutzer konfigurieren.',
  'You must upload a file.' => 'Sie müssen eine Datei hochladen.',
  'library' => 'Bibliothek',
);
