<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Requested category could not be found.' => 'Die angegebene Kategorie konnte nicht gefunden werden.',
  'Requested item could not be found.' => 'Der angegebene Eintrag konnte nicht gefunden werden.',
  'The category you want to create your document in could not be found!' => 'Die Kategorie, in dem Sie Ihr Dokument anlegen möchten, konnte nicht gefunden werden.',
  'The category you want to create your link in could not be found!' => 'Die Kategorie, in dem Sie Ihren Link anlegen möchten, konnte nicht gefunden werden.',
  'The item you want to edit could not be found!' => 'Der zu bearbeitende Eintrag konnte nicht gefunden werden!',
  'You miss the rights to add documents to public categories!' => 'Ihnen fehlen die Rechte um Dokumente zu öffentlichen Kategorien hinzuzufügen!',
  'You miss the rights to add documents!' => 'Ihnen fehlen die Rechte um Dokumente hinzuzufügen!',
  'You miss the rights to add links to public categories!' => 'Ihnen fehlen die Rechte um Links zu öffentlichen Kategorien hinzuzufügen!',
  'You miss the rights to add links!' => 'Ihnen fehlen die Rechte um Links hinzuzufügen!',
  'You miss the rights to add/edit items!' => 'Ihnen fehlen die Rechte um Einträge zu erstellen oder zu ändern!',
  'You miss the rights to delete this category!' => 'Ihnen fehlen die Rechte um diese Kategorie zu löschen!',
  'You miss the rights to delete this item!' => 'Ihnen fehlen die Rechte um diesen Eintrag zu löschen!',
  'You miss the rights to edit this category!' => 'Ihnen fehlen die Rechte um diese Kategorie zu bearbeiten!',
  'You miss the rights to edit this document!' => 'Ihnen fehlen die Rechte um dieses Dokument zu bearbeiten!',
  'You miss the rights to reorder categories!' => 'Ihnen fehlen die Rechte um Kategorien zu sortieren.',
  'You miss the rights to reorder items!' => 'Ihnen fehlen die Rechte um Einträge zu sortieren.',
);
