<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A disclaimer will be added to the public library.' => 'سيتم إضافة رسالة إخلاء مسؤولية لصفحة مكتبة الملفات.',
  'A public library will be added to the top menu. It contains all public library categories from all spaces.' => 'سيتم إضافة وصلة لمكتبة الملفات في القائمة الرئيسية, وتحتوي على كل الأقسام المنشورة للعامة من جميع الباحات.',
  'Disclaimer content' => 'محتويات رسالة إخلاء المسؤولية',
  'Disclaimer title' => 'عنوان الرسالة',
  'Disclaimer widget' => 'ودجت رسالة إخلاء المسؤولية',
  'Enable global public library.' => 'تفعيل مكتبة الملفات العامة.',
  'Extend link validation by a connection test.' => 'التأكد من صحة الوصلة عن طريق اختبار إتصال.',
  'Global public library' => 'مكتبة الملفات العامة',
  'Library Module Configuration' => 'إعدادات موديول المكتبة العامة.',
  'Library configuration' => 'إعدادات المكتبة العامة',
  'Only publishers/admins can add items to any category.' => 'فقط الناشرون ومشرفوا الموقع يستطيعون الإضافة على اي قسم.',
  'Show disclaimer widget in global public library.' => 'عرض خانة إخلاء المسؤولية في المكتبة العامة.',
  'Show selected library categories in a sidebar widget.' => 'عرض الأقسام المختارة من المكتبة العامة في القائمة الجانبية.',
  'You can configure extended functionality of this module for a space or user.' => 'يمكنك تغيير إعدادات إضافية لهذا الموديول لباحة او عضو محدد.',
);
