<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Confirm</strong> category deleting' => 'تأكيد رغبتك في <strong>حذف</strong> القسم',
  '<strong>Confirm</strong> item deleting' => 'تأكيد رغبتك في <strong>حذف</strong> الملف',
  '<strong>Create</strong> new category' => '<strong>قسم</strong> جديد',
  '<strong>Create</strong> new document' => '<strong>ملف</strong> جديد',
  '<strong>Create</strong> new link' => '<strong>وصلة</strong> جديدة',
  '<strong>Edit</strong> category' => 'تعديل<strong>قسم</strong>',
  '<strong>Edit</strong> document' => 'تعديل<strong>ملف</strong>',
  '<strong>Edit</strong> link' => 'تعديل<strong>وصلة</strong>',
  '<strong>Public</strong> libraries' => 'مكتبات<strong>منشورة للعامة</strong>',
  'A disclaimer will be added to the public library.' => 'سيتم إضافة رسالة إخلاء مسؤولية للمكتبة العامة.',
  'A public library will be added to the top menu. It contains all public library categories from all spaces.' => 'سيتم إضافة وصلة لمكتبة الملفات في القائمة الرئيسية, وتحتوي على كل الأقسام المنشورة للعامة من جميع الباحات.',
  'Add category' => 'إضافة قسم',
  'Add document' => 'إضافة ملف',
  'Add link' => 'إضافة وصلة',
  'Added a new document %document% to category "%category%".' => 'إضافة ملف جديد %document% للقسم "%category%".',
  'Added a new link %link% to category "%category%".' => 'إضافة وصلة جديدة %link% للقسم "%category%"',
  'All users can access items in public categories. Only publishers can add items.' => 'جميع الأعضاء لديهم الصلاحية لتحميل الملفات, فقط الناشرون والمشرفون لديهم صلاحية إضافة الملفات.',
  'Back to library' => 'عودة للمكتبة',
  'Cancel' => 'إلغاء الأمر',
  'Delete' => 'حذف',
  'Delete category' => 'حذف القسم',
  'Delete item' => 'حذف الملف',
  'Description' => 'الوصف',
  'Disclaimer' => 'إخلاء المسؤولية',
  'Disclaimer content' => 'رسالة إخلاء المسؤولية',
  'Disclaimer title' => 'عنوان رسالة إخلاء المسؤولية',
  'Disclaimer widget' => 'ودجت إخلاء المسؤولية',
  'Do you really want to delete this category? All connected items will be lost!' => 'هل أنت متأكد من رغبتك في حذف هذا القسم؟ جميع الملفات المدرجة فيه سيتم حذفها!',
  'Do you really want to delete this item?' => 'هل انت متأكد من رغبتك في حذف هذا الملف؟',
  'Document' => 'ملف',
  'Document date' => 'التاريخ',
  'Edit category' => 'تعديل القسم',
  'Edit item' => 'تعديل الملف',
  'Enable global public library.' => 'تفعيل المكتبة العامة.',
  'Extend link validation by a connection test.' => 'التأكد من صحة الوصلة عن طريق اختبار إتصال.',
  'File' => 'ملف',
  'Global public library' => 'المكتبة العامة',
  'ID' => 'ID',
  'If you upload multiple files, only the last file will be saved.' => 'إن قمت برع عدة ملفات سيتم الإحتفاظ بآخر واحد فقط.',
  'Library' => 'المكتبة',
  'Library Module Configuration' => 'إعدادات موديول المكتبة العامة',
  'Library configuration' => 'إعدادات المكتبة العامة',
  'LibraryCategory' => 'قسم المكتبة العامة',
  'Link' => 'وصلة',
  'No public categories have been added to any space library yet.' => 'لم يتم إضافة اي قسم للمكتبة العامة لأي باحه بعد.',
  'Only publishers/admins can add items to any category.' => 'فقط الناشرون و المشرفون يستطيعون رفع الملفات لأي قسم.',
  'Quick' => 'مختصر',
  'Save' => 'حفظ',
  'Set a custom disclaimer text or disable the disclaimer widget in the library module configuration.' => 'أكتب رسالة إخلاء مسؤولية او قم بإلغاء عرض ودجت رسالة إخلاء المسؤولية من إعدادات موديول المكتبة العامة.',
  'Show disclaimer widget in global public library.' => 'عرض خانة إخلاء المسؤولية في المكتبة العامة.',
  'Show selected library categories in a sidebar widget.' => 'عرض القسم المختار من المكتبة في القائمة الجانبية.',
  'Show this category in sidebar widget.' => 'عرض هذا القسم في القائمة الجانبية.',
  'Sort order' => 'ترتيب حسب',
  'The item order was successfully changed.' => 'تم تغيير ترتيب الملفات بنجاح!',
  'There have been no items or categories added to this space yet.' => 'لم تتم إضافة اي ملفات او أقسام لهذا الباحه بعد.',
  'There have been no public categories added to this space yet.' => 'لم يتم إضافة اي اقسام عامة لهذه الباحة.',
  'This is a public category.' => 'هذا قسم عام.',
  'Title' => 'العنوان',
  'URL' => 'عنوان الموقع',
  'You can configure extended functionality of this module for a space or user.' => 'يمكنك تغيير إعدادات إضافية لهذا الموديول لباحة او عضو محدد.',
  'You must upload a file.' => 'يجب أن تختار ملفاً لرفعه',
  'library' => 'المكتبة',
);
