<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Requested category could not be found.' => 'لم يتم إيجاد القسم المطلوب.',
  'Requested item could not be found.' => 'لم يتم إيجاد الملف المطلوب.',
  'The category you want to create your document in could not be found!' => 'لم يتم غيجاد القسم الذي رغبت في إضافة ملفك له!',
  'The category you want to create your link in could not be found!' => 'لم يتم ايجاد القسم الذي رغبت في إضافة الوصله إليه!',
  'The item you want to edit could not be found!' => 'لم يتم إيجاد الملف الذي رغبت في التعديل عليه!',
  'You miss the rights to add documents to public categories!' => 'ليست لديك الصلاحية لتعديل الملفات في الاقسام العامة!',
  'You miss the rights to add documents!' => 'ليست لديك الصلاحية لإضافة ملفات!',
  'You miss the rights to add links to public categories!' => 'ليست لديك الصلاحية لإضافة وصلات للأقسام العامة!',
  'You miss the rights to add links!' => 'ليست لديك الصلاحية لإضافة وصلات!',
  'You miss the rights to add/edit items!' => 'ليست لديك الصلاحية للإضافة او التعديل على الملفات!',
  'You miss the rights to delete this category!' => 'ليست لديك الصلاحية لحذف هذا القسم!',
  'You miss the rights to delete this item!' => 'ليست لديك الصلاحية لحذف هذا الملف!',
  'You miss the rights to edit this category!' => 'ليست لديك الصلاحية للتعديل على هذا القسم!',
  'You miss the rights to edit this document!' => 'ليست لديك الصلاحية للتعديل على هذا الملف!',
  'You miss the rights to reorder categories!' => 'ليست لديك الصلاحية لتغيير ترتيب الأقسام.',
  'You miss the rights to reorder items!' => 'ليست لديك الصلاحية لتغيير ترتيب الملفات.',
);
